import gleeunit
import gleeunit/should

import args.{PartOne, PartTwo}
import year2024/day08

const example = "
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"

pub fn main() {
  gleeunit.main()
}

pub fn part_one_test() {
  example |> day08.main(PartOne) |> should.equal("14")
}

pub fn part_two_test() {
  example |> day08.main(PartTwo) |> should.equal("34")
}
